### ISSUE TITLE
Implement Automated Testing for Discord Bot - Not possible to implement, has to be manually.

### ISSUE THREAD

**Issue by berkingurcan** [MinaFoundation/gptSurveySummarizer#46]
## Overview
To ensure the reliability and maintainability of our Discord bot, need to write automated testing. This will involve setting up integration tests between, end-to-end tests, and command-specific tests.

### Integration Tests
- Verify that different components of the bot work together as expected such as: Bot, Summarizer and DB.

### End-to-End Tests
- Simulate users who uses the discord bot to test commands

## Tools
- [cordejs](https://github.com/cordejs/corde?tab=readme-ov-file#-table-of-content) can be used but docs and maintenance does not look good :D
- Can be used sinon, mocha and chai to mock discord.js

@es92

**Comment by CristinaEche** [comment]
Berkin only left this task unfinished due to some problems. Here are his comments: 

However, there are significant problems in terms of testing Discord bots and in the project.

- Node Module Problem: I can't import functions in test folder, I really tried to solve this issue, consulted really experienced developers that I know. However, they could not solve as well. In my opinion, I could not convert the project to Typescript properly and it creates module import problems. I spent 3 days to solve it but no result 😦

- After solving the issue above, I can implement Unit tests, there is no problem.

- However, in integration and end-to-end testing, I made a lot of research, also asked people but there is no ideal or useful way to simulate bot interactions for testing purposes. Seems like, the best way to test it is testing manually and writing test report like we did with Cristina before.
